apiVersion: v1
kind: ConfigMap
metadata:
  name: swan-config
data:
{{- if (.Files.Glob "files/jupyterhub_form.html") }}
{{ (.Files.Glob "files/jupyterhub_form.html").AsConfig | indent 2 }}
{{- end }}
{{- if (.Files.Glob "files/swan_config.py") }}
{{ (.Files.Glob "files/swan_config.py").AsConfig | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: swan-secrets
data:
{{- if (.Files.Glob "files/private/check_ticket.sh") }}
{{ (.Files.Glob "files/private/check_ticket.sh").AsSecrets | indent 2 }}
{{- end }}
{{- if (.Files.Glob "files/private/delete_ticket.sh") }}
{{ (.Files.Glob "files/private/delete_ticket.sh").AsSecrets | indent 2 }}
{{- end }}
{{- if (.Files.Glob "files/private/eos_token.sh") }}
{{ (.Files.Glob "files/private/eos_token.sh").AsSecrets | indent 2 }}
{{- end }}
{{- if (.Files.Glob "files/private/hadoop_token.sh") }}
{{ (.Files.Glob "files/private/hadoop_token.sh").AsSecrets | indent 2 }}
{{- end }}
{{- if (.Files.Glob "files/private/webhdfs_token.sh") }}
{{ (.Files.Glob "files/private/webhdfs_token.sh").AsSecrets | indent 2 }}
{{- end }}
---