apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: swan
  namespace: {{ .Release.Namespace }}
data:
{{ if eq .Values.jupyterhub.hub.db.type "postgres" }}
  jupyterhub.hub.db.password: {{ (required "PostgresDB password must be specified (helm --set jupyterhub.hub.db.password=<redacted> ..)!" .Values.jupyterhub.hub.db.password) | b64enc | quote }}
{{ end }}
{{ if eq .Values.jupyterhub.auth.type "custom" }}
  jupyterhub.auth.custom.config.client_secret: {{ (required "OAuth password must be specified ( helm --set jupyterhub.auth.custom.config.client_secret=<redacted> )" .Values.jupyterhub.auth.custom.config.client_secret) | b64enc | quote }}
  jupyterhub.hub.extraEnv.JUPYTERHUB_CRYPT_KEY: {{ (required "Auth state crypt key has to be specified must be specified ( helm --set jupyterhub.hub.extraEnv.JUPYTERHUB_CRYPT_KEY=<redacted> )" .Values.jupyterhub.hub.extraEnv.JUPYTERHUB_CRYPT_KEY) | b64enc | quote }}
{{ end }}
  eos.cred: {{ (required "helm --set swan.secrets.eos.cred=$(base64 -w0 <path>)" .Values.swan.secrets.eos.cred) }}
  hadoop.cred: {{ (required "helm --set swan.secrets.hadoop.cred=$(base64 -w0 <path>)" .Values.swan.secrets.hadoop.cred) }}
  sparkk8s.cred: {{ (required "helm --set swan.secrets.sparkk8s.cred=$(base64 -w0 <path>)" .Values.swan.secrets.sparkk8s.cred) }}
  jupyterhub.hub.cookieSecret: {{ (required "helm --set jupyterhub.hub.cookieSecret=<redacted>)" .Values.jupyterhub.hub.cookieSecret) }}
  jupyterhub.proxy.secretToken: {{ (required "helm --set jupyterhub.proxy.secretToken=<redacted>)" .Values.jupyterhub.proxy.secretToken) }}
---
{{ if .Values.jupyterhub.ingress.enabled }}
{{ range .Values.jupyterhub.ingress.tls }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .secretName }}
  namespace: {{ $.Release.Namespace }}
data:
  tls.crt: {{ (required "helm --set swan.secrets.ingress.cert=$(base64 -w0 <path>)" $.Values.swan.secrets.ingress.cert) }}
  tls.key: {{ (required "helm --set swan.secrets.ingress.key=$(base64 -w0 <path>)" $.Values.swan.secrets.ingress.key) }}
{{ end }}
{{ end }}
