apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-swan-sft-cern-ch
provisioner: csi-cvmfsplugin
parameters:
  repository: sft.cern.ch
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvmfs-sft-cern-ch-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-swan-sft-cern-ch