{{ range .Values.jupyterhub.custom.cvmfs.repositories }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $.Release.Name }}-cvmfs-{{ . | replace "." "-" }}
provisioner: {{ $.Values.jupyterhub.custom.cvmfs.storageProvisioner }}
parameters:
  repository: {{ . }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvmfs-{{ . | replace "." "-" }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ $.Release.Name }}-cvmfs-{{ . | replace "." "-" }}
---
{{ end }}
{{ if .Values.jupyterhub.custom.cvmfs.prefetcher.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-prefetcher
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      name: cvmfs-prefetcher
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: cvmfs-prefetcher
      annotations:
        checksum/prefetch-script: {{ .Files.Get "files/cvmfs/cvmfs_prefetch_modules.sh" | sha256sum }}
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      {{ range .Values.jupyterhub.custom.cvmfs.repositories }}
      - name: cvmfs-{{ . | replace "." "-" }}
        persistentVolumeClaim:
          claimName: cvmfs-{{ . | replace "." "-" }}-pvc
      {{ end }}
      - name: cvmfs-prefetcher-config
        configMap:
          name: swan-scripts
          items:
          - key: cvmfs_prefetch_modules.sh
            path: cvmfs_prefetch_modules.sh
          defaultMode: 356 # 0544 perm
      containers:
      - name: cvmfs-puller
        image: {{ .Values.jupyterhub.custom.cvmfs.prefetcher.image.name }}:{{ .Values.jupyterhub.custom.cvmfs.prefetcher.image.tag }}
        imagePullPolicy: 'IfNotPresent'
        volumeMounts:
          {{ range .Values.jupyterhub.custom.cvmfs.repositories }}
          - name: cvmfs-{{ . | replace "." "-" }}
            mountPath: /cvmfs/{{ . }}
          {{ end }}
          - name: cvmfs-prefetcher-config
            mountPath: /etc/cvmfs-prefetcher/cvmfs_prefetch_modules.sh
            subPath: cvmfs_prefetch_modules.sh
{{ end }}