{{ range .Values.jupyterhub.custom.cvmfs.repositories }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs-{{ . | replace "." "-" }}
provisioner: csi-cvmfsplugin
parameters:
  repository: {{ . }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvmfs-{{ . | replace "." "-" }}-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: cvmfs-{{ . | replace "." "-" }}
---
{{ end }}
{{ if .Values.jupyterhub.custom.cvmfs.prefetcher.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cvmfs-prefetcher-config
data:
  cvmfs_prefetch_modules.sh: |-
    #!/bin/bash

    while true; do
        source /cvmfs/sft.cern.ch/lcg/views/LCG_96/x86_64-centos7-gcc8-opt/setup.sh && ( timeout 10s python -m ipykernel > /dev/null 2>&1 || true )
        if [ $? -ne 0 ]; then
            echo "Getting ipykernel failed"
        fi

        source /cvmfs/sft.cern.ch/lcg/views/LCG_96/x86_64-centos7-gcc8-opt/setup.sh && ( timeout 20s python -m JupyROOT.kernel.rootkernel > /dev/null 2>&1 || true )
        if [ $? -ne 0 ]; then
            echo "Getting JupyROOT.kernel.rootkernel failed"
        fi

        sleep 15m
    done

    exit 1
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-prefetcher
spec:
  selector:
    matchLabels:
      name: cvmfs-prefetcher
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: cvmfs-prefetcher
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      {{ range .Values.jupyterhub.custom.cvmfs.repositories }}
      - name: cvmfs-{{ . | replace "." "-" }}
        persistentVolumeClaim:
          claimName: cvmfs-{{ . | replace "." "-" }}-pvc
      {{ end }}
      - name: cvmfs-prefetcher-config
        configMap:
          name: cvmfs-prefetcher-config
          items:
          - key: cvmfs_prefetch_modules.sh
            path: cvmfs_prefetch_modules.sh
          defaultMode: 356 # 0544 perm
      containers:
      - name: cvmfs-puller
        image: {{ .Values.jupyterhub.custom.cvmfs.prefetcher.image.name }}:{{ .Values.jupyterhub.custom.cvmfs.prefetcher.image.tag }}
        imagePullPolicy: 'IfNotPresent'
        volumeMounts:
          {{ range .Values.jupyterhub.custom.cvmfs.repositories }}
          - name: cvmfs-{{ . | replace "." "-" }}
            mountPath: /cvmfs/{{ . }}
          {{ end }}
          - name: cvmfs-prefetcher-config
            mountPath: /etc/cvmfs-prefetcher/cvmfs_prefetch_modules.sh
            subPath: cvmfs_prefetch_modules.sh
{{ end }}