apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-swan-sft-cern-ch
provisioner: csi-cvmfsplugin
parameters:
  repository: sft.cern.ch
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cvmfs-sft-cern-ch-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-swan-sft-cern-ch
---
{{ if .Values.swan.cvmfs.prefetcher.enable }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cvmfs-prefetcher
spec:
  selector:
    matchLabels:
      name: cvmfs-prefetcher
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        name: cvmfs-prefetcher
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cvmfs-sft-cern-ch
        persistentVolumeClaim:
          claimName: cvmfs-sft-cern-ch-pvc
      containers:
      - name: cvmfs-puller
        image: gitlab-registry.cern.ch/db/spark-service/docker-registry/cvmfs-prefetcher:latest
        imagePullPolicy: 'Always'
        volumeMounts:
          - name: cvmfs-sft-cern-ch
            mountPath: /cvmfs/sft.cern.ch
{{ end }}