jupyterhub:
  singleuser:
    uid: 0
    fsGid: 0
    storage:
      type: none
    image:
      name: "gitlab-registry.cern.ch/swan/docker-images/systemuser"
      tag: "swandb"
      pullPolicy: "Always"
    cloudMetadata:
      enabled: true
    networkPolicy:
      enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/frontend-entry-points: http, https
      traefik.ingress.kubernetes.io/redirect-entry-point: https
    tls:
      - secretName: swan-tls-cert
    # placeholder for hostname
    hosts:
  proxy:
    service:
      type: ClusterIP
    chp:
      image:
        name: "jupyterhub/configurable-http-proxy"
        tag: "4.2.0"
        pullPolicy: "IfNotPresent"
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
    # placeholder for hub secret token
    secretToken:
  hub:
    uid: 0
    fsGid: 0
    deploymentStrategy:
      type: RollingUpdate
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    image:
      name: "gitlab-registry.cern.ch/swan/docker-images/jupyterhub"
      tag: "1.1.0-cern3"
      pullPolicy: "Always"
    extraVolumeMounts:
      - name: swan-jh
        mountPath: /srv/jupyterhub/options_form_config.json
        subPath: options_form_config.json
      - name: swan-jh
        mountPath: /srv/jupyterhub/swan_config.py
        subPath: swan_config.py
      - name: swan-secrets
        mountPath: /srv/jupyterhub/private/eos.cred
        subPath: eos.cred
      - name: swan-secrets
        mountPath: /srv/jupyterhub/private/hadoop.cred
        subPath: hadoop.cred
      - name: swan-secrets
        mountPath: /srv/jupyterhub/private/sparkk8s.cred
        subPath: sparkk8s.cred
      - name: swan-cull-scripts
        mountPath: /srv/jupyterhub/culler/check_ticket.sh
        subPath: cull_check_ticket.sh
      - name: swan-cull-scripts
        mountPath: /srv/jupyterhub/culler/delete_ticket.sh
        subPath: cull_delete_ticket.sh
      - name: swan-tokens-scripts
        mountPath: /srv/jupyterhub/private/eos_token.sh
        subPath: eos_token.sh
      - name: swan-tokens-scripts
        mountPath: /srv/jupyterhub/private/hadoop_token.sh
        subPath: hadoop_token.sh
      - name: swan-tokens-scripts
        mountPath: /srv/jupyterhub/private/webhdfs_token.sh
        subPath: webhdfs_token.sh
      - name: swan-tokens-scripts
        mountPath: /srv/jupyterhub/private/sparkk8s_token.sh
        subPath: sparkk8s_token.sh
      - name: cvmfsd
        mountPath: /cvmfs
        mountPropagation: HostToContainer
    extraVolumes:
      - name: cvmfsd
        hostPath:
          path: /var/cvmfs
      - name: swan-jh
        configMap:
          name: swan-scripts
          items:
          - key: options_form_config.json
            path: options_form_config.json
          - key: swan_config.py
            path: swan_config.py
      - name: swan-cull-scripts
        configMap:
          name: swan-scripts
          items:
          - key: cull_check_ticket.sh
            path: cull_check_ticket.sh
          - key: cull_delete_ticket.sh
            path: cull_delete_ticket.sh
          defaultMode: 356 # 0544 perm
      - name: swan-tokens-scripts
        configMap:
          name: swan-scripts-env-prod
          items:
          - key: hadoop_token.sh
            path: hadoop_token.sh
          - key: webhdfs_token.sh
            path: webhdfs_token.sh
          - key: eos_token.sh
            path: eos_token.sh
          - key: sparkk8s_token.sh
            path: sparkk8s_token.sh
          defaultMode: 356 # 0544 perm
      - name: swan-secrets
        secret:
          secretName: swan
          items:
          - key: eos.cred
            path: eos.cred
          - key: hadoop.cred
            path: hadoop.cred
          - key: sparkk8s.cred
            path: sparkk8s.cred
    extraConfig:
      swanConf: |
        exec(open('/srv/jupyterhub/swan_config.py').read())
    extraEnv:
      OAUTH2_AUTHORIZE_URL: https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/auth
      OAUTH2_TOKEN_URL: https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/token
      # placeholder for client id
      APP_CLIENT_ID:
      # placeholder for callback url
      OAUTH_CALLBACK_URL: 
      # placeholder for hub auth state cryptographic key
      JUPYTERHUB_CRYPT_KEY:
    db:
      type: postgres
      # placeholder for postgres connection url
      url: 
      # placeholder for postgres password
      password:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/path: /hub/metrics
    networkPolicy:
      enabled: false
    # placeholder for hub cookieSecret
    cookieSecret:
  auth:
    type: custom
    admin:
      users:
        - pkothuri
        - pmrowczy
    custom:
      className: CERNOAuthenticator
      config:
        login_service: keycloak
        token_url: https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/token
        userdata_url: https://auth.cern.ch/auth/realms/cern/protocol/openid-connect/userinfo
        groupdata_url: ""
        userdata_method: GET
        userdata_params: {'state': 'state'}
        username_key: cern_upn
        enable_auth_state: true
        auto_login: false
        auth_refresh_age: 3600
        refresh_pre_spawn: true
        # placeholder for oauth client_id to be filled by secrets.yaml
        client_id:
        # placeholder for oauth secret to be filed by secrets.yaml
        client_secret:
  rbac:
    enabled: true
  scheduling:
    userScheduler:
      enabled: false
    podPriority:
      enabled: false
  prePuller:
    hook:
      enabled: true
    continuous:
      enabled: false
  debug:
    enabled: true
  # disable upstream cull, but enable custom one
  cull:
    enabled: false
  custom:
    cull:
      enabled: true
      period: 600
      checkEosAuth:
        enabled: true
# placeholders for swan credentials
swan:
  secrets:
    eos:
      cred:
    hadoop:
      cred:
    sparkk8s:
      cred:
    ingress:
      cert:
      key:
